"""add zipcode_id to company table

Revision ID: a1828642ba78
Revises: 213602dbf311
Create Date: 2025-10-10 20:43:44.202657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1828642ba78'
down_revision: Union[str, Sequence[str], None] = '213602dbf311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('zipcode_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'companies', 'master_zipcodes', ['zipcode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'zipcode_id')
    # ### end Alembic commands ###
