"""Add soft deletes

Revision ID: deb319db54ca
Revises: a1828642ba78
Create Date: 2025-10-14 09:30:25.283970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb319db54ca'
down_revision: Union[str, Sequence[str], None] = 'a1828642ba78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'deleted_at')
    op.drop_column('branches', 'deleted_at')
    # ### end Alembic commands ###
