"""Adding soft delete to all crud

Revision ID: e554c19dff79
Revises: deb319db54ca
Create Date: 2025-10-14 10:52:43.504605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e554c19dff79'
down_revision: Union[str, Sequence[str], None] = 'deb319db54ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('partner_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('partners', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('warehouses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'deleted_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('products', 'deleted_at')
    op.drop_column('product_categories', 'deleted_at')
    op.drop_column('partners', 'deleted_at')
    op.drop_column('partner_categories', 'deleted_at')
    op.drop_column('company_categories', 'deleted_at')
    # ### end Alembic commands ###
